<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mall</groupId>
        <artifactId>cloud-mall</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>mall-modules</artifactId>
    <packaging>pom</packaging>
    <name>mall-modules</name>

    <modules>
        <module>mall-ai</module>
        <module>mall-cuisine</module>
        <module>mall-interaction</module>
        <module>mall-user</module>
        <module>mall-support</module>
        <module>mall-member</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.mall</groupId>
            <artifactId>mall-common</artifactId>
        </dependency>
    </dependencies>
</project>
